# Site settings 配置站点
title: '独行深山'
description: '南京 个人开发者 软件开发 公众号开发 小程序开发 App开发 微信开发 系统开发'
keyword: '南京 个人开发者 软件开发 公众号开发 小程序开发 App开发 商城开发 系统开发'
url: 'http://wangxuan.me' # your host

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'
  fastpages: '/fastpages/'
  about: '/about.html'

# Author 配置博主信息
author: '王一刀'
nickname: '王一刀'
bio: '看书，听歌，写程序'
avatar: '/assets/img/profile.png'

# Search
search: true

# Night mode
nightMode: true

# Comments
disqus: false
disqus_url: ''

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站url: weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  weibo: '//weibo.com/halfg0d'
  douban: '//douban.com/people/stardust1900'
  twitter: '//twitter.com/halfg0d'
  github: '//github.com/stardust1900'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

RSS: true

# Plugins
plugins: [jekyll-paginate,jekyll-sitemap]
